spring.application.name=be-vulnerable

# Porta del backend VULNERABILE
server.port=8081

# Database H2 in memoria: DB_CLOSE_DELAY=-1 lo tiene vivo per tutta la durata dell'app
spring.datasource.url=jdbc:h2:mem:vulndb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Esegue schema.sql + data.sql all'avvio (crea e popola la tabella utenti)
spring.sql.init.mode=always
